{
    'AA': {
        'DD': (1, ['DD']),
        'II': (1, ['II']),
        'BB': (1, ['BB']),
        'CC': (2, ['DD', 'CC']),
        'EE': (2, ['DD', 'EE']),
        'JJ': (2, ['II', 'JJ']),
        'FF': (3, ['DD', 'EE', 'FF']),
        'GG': (4, ['DD', 'EE', 'FF', 'GG']),
        'HH': (5, ['DD', 'EE', 'FF', 'GG', 'HH']),
        },
    'BB': {
        'CC': (1, ['CC']),
        'AA': (1, ['AA']),
        'DD': (2, ['CC', 'DD']),
        'II': (2, ['AA', 'II']),
        'EE': (3, ['CC', 'DD', 'EE']),
        'JJ': (3, ['AA', 'II', 'JJ']),
        'FF': (4, ['CC', 'DD', 'EE', 'FF']),
        'GG': (5, ['CC', 'DD', 'EE', 'FF', 'GG']),
        'HH': (6, [
            'CC',
            'DD',
            'EE',
            'FF',
            'GG',
            'HH',
            ]),
        },
    'CC': {
        'DD': (1, ['DD']),
        'BB': (1, ['BB']),
        'AA': (2, ['DD', 'AA']),
        'EE': (2, ['DD', 'EE']),
        'II': (3, ['DD', 'AA', 'II']),
        'FF': (3, ['DD', 'EE', 'FF']),
        'JJ': (4, ['DD', 'AA', 'II', 'JJ']),
        'GG': (4, ['DD', 'EE', 'FF', 'GG']),
        'HH': (5, ['DD', 'EE', 'FF', 'GG', 'HH']),
        },
    'DD': {
        'CC': (1, ['CC']),
        'AA': (1, ['AA']),
        'EE': (1, ['EE']),
        'BB': (2, ['CC', 'BB']),
        'II': (2, ['AA', 'II']),
        'FF': (2, ['EE', 'FF']),
        'JJ': (3, ['AA', 'II', 'JJ']),
        'GG': (3, ['EE', 'FF', 'GG']),
        'HH': (4, ['EE', 'FF', 'GG', 'HH']),
        },
    'EE': {
        'FF': (1, ['FF']),
        'DD': (1, ['DD']),
        'GG': (2, ['FF', 'GG']),
        'CC': (2, ['DD', 'CC']),
        'AA': (2, ['DD', 'AA']),
        'HH': (3, ['FF', 'GG', 'HH']),
        'BB': (3, ['DD', 'CC', 'BB']),
        'II': (3, ['DD', 'AA', 'II']),
        'JJ': (4, ['DD', 'AA', 'II', 'JJ']),
        },
    'FF': {
        'EE': (1, ['EE']),
        'GG': (1, ['GG']),
        'DD': (2, ['EE', 'DD']),
        'HH': (2, ['GG', 'HH']),
        'CC': (3, ['EE', 'DD', 'CC']),
        'AA': (3, ['EE', 'DD', 'AA']),
        'BB': (4, ['EE', 'DD', 'CC', 'BB']),
        'II': (4, ['EE', 'DD', 'AA', 'II']),
        'JJ': (5, ['EE', 'DD', 'AA', 'II', 'JJ']),
        },
    'GG': {
        'FF': (1, ['FF']),
        'HH': (1, ['HH']),
        'EE': (2, ['FF', 'EE']),
        'DD': (3, ['FF', 'EE', 'DD']),
        'CC': (4, ['FF', 'EE', 'DD', 'CC']),
        'AA': (4, ['FF', 'EE', 'DD', 'AA']),
        'BB': (5, ['FF', 'EE', 'DD', 'CC', 'BB']),
        'II': (5, ['FF', 'EE', 'DD', 'AA', 'II']),
        'JJ': (6, [
            'FF',
            'EE',
            'DD',
            'AA',
            'II',
            'JJ',
            ]),
        },
    'HH': {
        'GG': (1, ['GG']),
        'FF': (2, ['GG', 'FF']),
        'EE': (3, ['GG', 'FF', 'EE']),
        'DD': (4, ['GG', 'FF', 'EE', 'DD']),
        'CC': (5, ['GG', 'FF', 'EE', 'DD', 'CC']),
        'AA': (5, ['GG', 'FF', 'EE', 'DD', 'AA']),
        'BB': (6, [
            'GG',
            'FF',
            'EE',
            'DD',
            'CC',
            'BB',
            ]),
        'II': (6, [
            'GG',
            'FF',
            'EE',
            'DD',
            'AA',
            'II',
            ]),
        'JJ': (7, [
            'GG',
            'FF',
            'EE',
            'DD',
            'AA',
            'II',
            'JJ',
            ]),
        },
    'II': {
        'AA': (1, ['AA']),
        'JJ': (1, ['JJ']),
        'DD': (2, ['AA', 'DD']),
        'BB': (2, ['AA', 'BB']),
        'CC': (3, ['AA', 'DD', 'CC']),
        'EE': (3, ['AA', 'DD', 'EE']),
        'FF': (4, ['AA', 'DD', 'EE', 'FF']),
        'GG': (5, ['AA', 'DD', 'EE', 'FF', 'GG']),
        'HH': (6, [
            'AA',
            'DD',
            'EE',
            'FF',
            'GG',
            'HH',
            ]),
        },
    'JJ': {
        'II': (1, ['II']),
        'AA': (2, ['II', 'AA']),
        'DD': (3, ['II', 'AA', 'DD']),
        'BB': (3, ['II', 'AA', 'BB']),
        'CC': (4, ['II', 'AA', 'DD', 'CC']),
        'EE': (4, ['II', 'AA', 'DD', 'EE']),
        'FF': (5, ['II', 'AA', 'DD', 'EE', 'FF']),
        'GG': (6, [
            'II',
            'AA',
            'DD',
            'EE',
            'FF',
            'GG',
            ]),
        'HH': (7, [
            'II',
            'AA',
            'DD',
            'EE',
            'FF',
            'GG',
            'HH',
            ]),
        },
    }